name: Generate Pacman

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write   # 🔥 THIS FIXES ERROR 128

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate animation
        uses: Platane/snk@v3
        with:
          github_user_name: MrFantastico007
          outputs: dist/pacman.svg?color_snake=%23F4C430&color_dots=%23FDF6E3,%23FDE68A,%23FCD34D,%23F59E0B,%23DC2626

      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
